# Nixpacks configuration for parti-chat web app
[variables]
NIXPACKS_BUILD_SYSTEM = "bun"
NODE_ENV = "production"
PORT = "3000"

[phases.setup]
nixPkgs = ["bun", "nodejs_20", "python3", "postgresql"]

[phases.install]
cmds = ["bun install --frozen-lockfile"]

[phases.build]
cmds = [
    "bun run build --filter=web",
    "echo 'Web app build completed'",
    "ls -la apps/web/.next/"
]

[start]
# Start the web app
cmd = "cd apps/web && bun run start"