# Nixpacks configuration for parti-chat monorepo - full-stack
[variables]
NIXPACKS_BUILD_SYSTEM = "bun"
NODE_ENV = "production"
WEB_PORT = "3000"
SERVER_PORT = "3001"

[phases.setup]
nixPkgs = ["bun", "nodejs_20", "python3", "postgresql"]

[phases.install]
cmds = [
    "bun install --frozen-lockfile",
    "bun add -g pm2"
]

[phases.build]
cmds = [
    "bun run build",
    "echo 'Build completed, checking builds...'",
    "ls -la apps/server/.next/",
    "ls -la apps/web/.next/"
]

[start]
# Start both applications with PM2
cmd = "pm2-runtime start ecosystem.config.js"