[phases.setup]
nixPkgs = ["nodejs", "bun"]

[phases.install]
cmds = [
  "bun install --frozen-lockfile"
]

[phases.build]
cmds = [
  "bun run build"
]

[start]
cmd = "bun run start"

[variables]
NODE_ENV = "production"
PORT = "3001"